---
title: "Predictive Wavelength Switching Project"
# This code provides the best wavelength choices for 3-add events with 8 pre-existing channels
 
output: bookdown::gitbook
site: bookdown::bookdown_site
---
```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, eval = T)
library(caret); library(stringr); library(dplyr); library(readxl)

library(gtools)
```

# Index

Predict the value of the gain at other channels by having few input channels
 
hello !!!!!!


#Read the data 

<!-- this does not print -->


```{r data}
# change the follwing path accordingly. Note that zara3M folder includes Fully Loaded Band.xlsx and Input.xlsx files
setwd("~/Camp1/idea/zara3M/")
sss <- dir(".")
library(stringr)
www <- str_detect(sss, ".xlsx") 

sss[www]


library(dplyr)
rm(ddf)
all_gains <- str_c("g_", str_pad(1:80, 2, pad = "0"))
all_gains2 <- (str_pad(1:80, 2, pad = "0"))
#make id for each freq
temp_df <- read_excel("Fully Loaded Band.xlsx", skip = 1)

names(temp_df) <- c("Freq", "wl", "PowerIn", "PowerOut", "Gain")

temp_df <- temp_df %>%
  mutate_each(funs(as.numeric))

freq_map <- temp_df %>%
  arrange(Freq) %>%
  mutate(f_id = all_gains,num_id = all_gains2) %>%
  select(Freq, f_id,num_id)

freq_map

for(nn in sss[www][1:5]){
  temp_df <- read_excel(nn, skip = 1)
  

  # if excel file has only one col, it was not formated correclty. Correct this in this "if"
  if(ncol(temp_df) == 1) { 
    library(tidyr)
    names(temp_df) <- str_replace(names(temp_df), "\t$", "")
    temp_df <- temp_df %>%
      separate_(col = names(temp_df)[1], 
                into = c("Freq", "wl", "PowerIn", "PowerOut", "Gain"),
                sep = "\t.", remove = T, convert = T)
  }
  
  names(temp_df) <- c("Freq", "wl", "PowerIn", "PowerOut", "Gain")
  
  temp_df <- temp_df %>%
    mutate_each(funs(as.numeric)) %>%
    full_join(freq_map)
  
  temp_df$name <- nn
  
  
  for(dd in temp_df$f_id){
    root_gain <- filter(temp_df, f_id == dd) %>% select(Gain) %>% as.numeric()
    root_freq <- filter(temp_df, f_id == dd) %>% select(Freq) %>% as.numeric()

    temp_df[, str_c(dd, "_over")] <- (10^(temp_df$Gain/10)) / (10^(root_gain/10))
  }

  if(!exists("ddf")) {
    temp_df <- temp_df[, sort(names(temp_df))]
    ddf <- temp_df
  }else{
      ddf <- rbind(ddf, temp_df)
      }

}

  
# check validity of results
ddf %>% filter(g_01_over == 1) %>% select(Freq, name)
ddf %>% filter(g_15_over == 1) %>% select(Freq, name)

# create number of channel coloumn
ddf <- ddf %>% 
  group_by(name) %>% 
  mutate(num_of_chanels = sum(! is.na(Gain))) %>%
  ungroup()

ddf %>% group_by(name) %>% summarise(unique(num_of_chanels))


filter(temp_df, f_id == dd)

library(ggplot2)

# Plot Output power spectrum over channel 45th power with a small power gap between fully loaded band and input channel loading

ggplot(ddf, aes(y= g_45_over, x = Freq)) + 
  geom_point(aes(color = name, shape = factor(num_of_chanels))) 


library(plotly)
ggplotly()

ggplot(ddf, aes(y= g_64_over, x = Freq)) +
  geom_point(aes(color = name, shape = factor(num_of_chanels))) 

ggplotly()




compare_test <- function(ddf, file_1, margin) {

# By stacking all pre-existing channel in xx file, We make sure the newly proposed channels are not repetitive.
v = 1
   
df_test <<- filter(ddf, name == file_1) %>%
    select(starts_with("num_id"),starts_with("Freq"), starts_with("f_id"), ends_with("15_over"), ends_with("21_over"), ends_with("27_over"), ends_with("33_over"), ends_with("39_over"), ends_with("45_over"), ends_with("51_over"), ends_with("46_over")) %>% 
    
filter((abs(g_15_over - v) < margin) & (abs(g_21_over - v) < margin)& (abs(g_27_over - v) < margin)& (abs(g_33_over - v) < margin)& (abs(g_39_over - v) < margin)& (abs(g_45_over - v) < margin)& (abs(g_51_over - v) < margin)& (abs(g_46_over - v) < margin))
  df_test
}

df2NotNA <- c("g_15", "g_21", "g_27", "g_33", "g_39", "g_45", "g_51", "g_46")
#0.01551
xx <<- compare_test(ddf, sss[www][1], margin = 1) %>%
  #sum_ans <<- sum(xx$g_33_over, na.rm = T)
  filter(! f_id %in% df2NotNA ) 



# b parameter defines the number of newly added wavelengths
b=3 

# a parameter defines the number of wavelengths after add events
a=11
p=a
## zz1 defines the total number of pissible combination to pick 3 wavelenths out of 80 (excluing pre-existing wavelengths)
zz1 <-combn(xx$g_15_over, b, simplify=F)
# zzz2 parameter gives the f_id of the 3 newly proposed channels. Type: zzz2[( k parameter value)]
###################################################
###########Algorithm OUTCOMEs
zzz2 <-combn(xx$f_id, b, simplify=F)
# zzz4 parameter gives the num-id of the 3 newly proposed channels. Type: zzz4[( k parameter value)]
zzz4 <-combn(xx$num_id, b, simplify=F)
# zzz3 parameter gives the frequencies of the 3 newly proposed channels. This paprameter is the main OUTCOME of this algorithm. Type: zzz3[( k parameter value)]
zzz3 <-combn(xx$Freq, b, simplify=F)
####################################################
c<-1
k<-1

# m paramete defines the gap for diveregence of power between ripples, the ideal value for m is 0.
m=0.08

m3=m
############## Algorithm Core 

while(c <= length(zz1)){
 
dff3 <<- filter(ddf, name=="Fully Loaded Band.xlsx",(num_id == 15)  | (num_id == 21)| (num_id == 27)| (num_id == 33)| (num_id == 39)| (num_id == 45)| (num_id == 46)| (num_id == 51)| (num_id == as.numeric(zzz4[[k]][1]))| (num_id == as.numeric(zzz4[[k]][2]))| (num_id == as.numeric(zzz4[[k]][3])))

  if (
    (abs(sum(dff3$g_15_over, na.rm = T) - a) > m3) | (abs(sum(dff3$g_21_over, na.rm = T) - a) > m3)| (abs(sum(dff3$g_46_over, na.rm = T) - a) > m3) | (abs(sum(dff3$g_27_over, na.rm = T) - a) > m3) | (abs(sum(dff3$g_33_over, na.rm = T) - a) > m3) | (abs(sum(dff3$g_39_over, na.rm = T) - a) > m3) | (abs(sum(dff3$g_45_over, na.rm = T) - a) > m3) | (abs(sum(dff3$g_51_over, na.rm = T) - a) > m3)  | (abs(sum(dff3[1:p, str_c(zzz2[[k]][1], "_over")], na.rm = T) - a) > m) | (abs(sum(dff3[1:p, str_c(zzz2[[k]][2], "_over")], na.rm = T) - a) > m) | (abs(sum(dff3[1:p, str_c(zzz2[[k]][3], "_over")], na.rm = T) - a) > m) 
        
  ){
    k <- k+1
    }    
   

  c <- c+1
}



```
